# Generated by Django 3.2.7 on 2021-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostreecommit',
            name='relative_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostreeconfig',
            name='relative_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostreeobject',
            name='relative_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostreeref',
            name='relative_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostreesummary',
            name='relative_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ostreecommit',
            unique_together={('checksum', 'relative_path')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreeconfig',
            unique_together={('sha256', 'relative_path')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreeobject',
            unique_together={('checksum', 'relative_path')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreeref',
            unique_together={('name', 'commit', 'relative_path')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreesummary',
            unique_together={('sha256', 'relative_path')},
        ),
    ]
