# Generated by Django 3.2.6 on 2021-08-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_encrypt_remote_fields'),
        ('ostree', '0002_create_ostree_objs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OstreeSummary',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ostree_ostreesummary', serialize=False, to='core.content')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('sha256',)},
            },
            bases=('core.content',),
        ),
        migrations.AddField(
            model_name='ostreeconfig',
            name='sha256',
            field=models.CharField(db_index=True, default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostreeremote',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ostreeconfig',
            unique_together={('sha256',)},
        ),
        migrations.DeleteModel(
            name='OstreePublication',
        ),
    ]
