# Generated by Django 3.2.6 on 2021-09-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_rbaccontentguard'),
        ('ostree', '0003_update_ostree_objs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OstreeRef',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ostree_ostreeref', serialize=False, to='core.content')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('commit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refs_commit', to='ostree.ostreecommit')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('name', 'commit')},
            },
            bases=('core.content',),
        ),
        migrations.DeleteModel(
            name='OstreeRefsHead',
        ),
    ]
