# Generated by Django 4.2.9 on 2024-02-06 10:31

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_alter_remoteartifact_md5_alter_remoteartifact_sha1_and_more'),
        ('ostree', '0007_add_model_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ostreecommit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ostreeconfig',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ostreecontent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ostreeobject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ostreeref',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ostreesummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ostreecommit',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='ostreeconfig',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='ostreecontent',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='ostreeobject',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='ostreeref',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='ostreesummary',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='ostreecommit',
            unique_together={('checksum', 'relative_path', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreeconfig',
            unique_together={('sha256', 'relative_path', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreecontent',
            unique_together={('relative_path', 'digest', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreeobject',
            unique_together={('checksum', 'relative_path', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreeref',
            unique_together={('name', 'commit', 'relative_path', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='ostreesummary',
            unique_together={('sha256', 'relative_path', '_pulp_domain')},
        ),
    ]
